routes/web.php
<?php

use App\Http\Controllers\HomeController;
use App\Http\Controllers\SiswaController;

use App\Setting;
use App\Siswa;
use App\Banner;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

Route::get('/', 'HomeController@index');
Route::get('/home', 'HomeController@index');
Route::get('/prosedur', 'HomeController@prosedur');
Route::get('/agenda', 'HomeController@agenda');

Auth::routes();

Route::group(['middleware'=>['auth']], function()
{
  Route::get('logout', '\App\Http\Controllers\Auth\LoginController@logout');
  Route::resource('siswa', 'SiswaController');
  Route::resource('ortu', 'OrtuController');
  Route::get('datalengkap', 'SiswaController@datalengkap');
  Route::get('getpdf/{id?}', 'SiswaController@getPdf');
  Route::get('dashboard', 'HomeController@dashboard');

});

Route::group(['middleware'=>['auth', 'role:admin']], function()
{
  Route::resource('statis', 'StatisController');
  Route::resource('slide', 'SlideshowController');
  Route::resource('banner', 'BannerController');
  Route::resource('user', 'UserController');
  Route::resource('setting', 'SettingController');
  Route::get('datapendaftar/{jenjang?}', 'HomeController@dataPendaftar');
  Route::get('backup', 'HomeController@backup');
  Route::get('viewdata/{id?}', 'HomeController@viewData');
  Route::post('ubahstatus', 'HomeController@ubahStatus');
  Route::get('downloadexcel/{jenjang?}', 'HomeController@downloadExcel');
});


View::composer('sidebar', function($view){
  $view->banner = App\Banner::where('publish', 'Y')->get();
  if (Auth::check())
  {
    $view->siswa = App\Siswa::where('user_id',Auth::user()->id)->first();
  }
});

app/Slideshow.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Slideshow extends Model
{
    protected $fillable = ['judul', 'keterangan', 'keterangan2', 'link', 'image', 'publish']; 
}

app/Http/Controllers/SlideshowController.php
<?php

namespace App\Http\Controllers;
use Illuminate\Http\Request;
use App\Slideshow;
use Session;
use Image;
use File;

class SlideshowController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data['slide'] = Slideshow::orderBY('id', 'desc')->paginate(5);
        return view('slideshow.index', $data)->with('no', 1);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
      $data['page_title'] = 'Management Slideshow';
      return view('slideshow.create', $data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, ['judul'=>'required',
                                   'image'=>'required']);

        if(!empty($request->file('image'))){
          $image = time().$request->file('image')->getClientOriginalName();
          $request->file('image')->move('images/slideshow/', $image);
          $img = Image::make(public_path().'/images/slideshow/'.$image)->resize(1080,500)->save();

          File::copy(public_path().'/images/slideshow/'.$image, public_path().'/images/slideshow/thumb/'.$image);
          $img2 = Image::make(public_path().'/images/slideshow/thumb/'.$image)->resize(200,100)->save();

        }else{
          $image = '';
        }

        $data = $request->all();
        $data['image'] = $image;
        $data['publish'] = 'Y';
        Slideshow::create($data);

        Session::flash('flash_notification', [
                'level'=>'success',
                'message'=>'Berhasil menyimpan slideshow <b>'.$request['judul'].'</b>'
              ]);
        return redirect(route('slide.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data['page_title'] = 'Management Slideshow';
        $data['slide'] = Slideshow::findOrFail($id);
        return view('slideshow.edit', $data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
      $this->validate($request, ['judul'=>'required',
                                 'image'=>'sometimes']);
      $slide = Slideshow::findOrFail($id);
      if(!empty($request->file('image'))){
        File::delete(public_path().'/images/slideshow/'.$slide->image);
        File::delete(public_path().'/images/slideshow/thumb/'.$slide->image);

        $image = time().$request->file('image')->getClientOriginalName();
        $request->file('image')->move('images/slideshow/', $image);
        Image::make(public_path().'/images/slideshow/'.$image)->resize(1080,425)->save();

        File::copy(public_path().'/images/slideshow/'.$image, public_path().'/images/slideshow/thumb/'.$image);
        Image::make(public_path().'/images/slideshow/thumb/'.$image)->resize(200,100)->save();
      }else{
        $image = $slide->image;
      }

      $data = $request->all();
      $data['image'] = $image;
      $slide->update($data);

      Session::flash('flash_notification', [
              'level'=>'info',
              'message'=>'Berhasil mengubah slideshow <b>'.$request['judul'].'</b>'
            ]);
      return redirect(route('slide.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $slide = Slideshow::findOrFail($id);
        File::delete(public_path().'/images/slideshow/'.$slide->image);
        File::delete(public_path().'/images/slideshow/thumb/'.$slide->image);
        Session::flash('flash_notification', [
                'level'=>'danger',
                'message'=>'Berhasil menghapus slideshow <b>'.$slide['judul'].'</b>'
              ]);
        $slide->delete();
        return redirect(route('slide.index'));
    }
}

resources/views/slideshow/create.blade.php
@extends('style')
@section('content')
          <div class="panel panel-success">
            <div class="panel-heading">
              <h3 class="panel-title">Tambah Slideshow</h3>
            </div>
            <div class="panel-body">
              {!! Form::open(['method' => 'POST', 'route' => 'slide.store', 'class' => 'form-horizontal', 'files'=>true]) !!}

              @include('slideshow.form')

              <div class="btn-group pull-right">
                <a href="{{ route('slide.index') }}" class="btn btn-warning">Batal</a>
                {!! Form::submit("Simpan", ['class' => 'btn btn-success']) !!}
              </div>
              {!! Form::close() !!}
            </div>
          </div>

@endsection

resources/views/slideshow/edit.blade.php
@extends('style')
@section('content')
  <div class="panel panel-success">
    <div class="panel-heading">
      <h3 class="panel-title">Edit Slideshow</h3>
    </div>
    <div class="panel-body">
      {!! Form::model($slide, ['route' => ['slide.update', $slide->id], 'method' => 'PUT', 'class'=>'form-horizontal', 'files'=>true]) !!}

          @include('slideshow.form')

          <div class="btn-group pull-right">
              <a href="{{ route('slide.index') }}" class="btn btn-warning">Batal</a>
              {!! Form::submit("Simpan", ['class' => 'btn btn-success']) !!}
          </div>

      {!! Form::close() !!}
    </div>
    <div class="panel-footer">

    </div>
  </div>
@endsection

resources/views/slideshow/form.blade.php
<div class="form-group{{ $errors->has('judul') ? ' has-error' : '' }}">
    {!! Form::label('judul', 'Judul slideshow', ['class' => 'col-sm-3 control-label']) !!}
    <div class="col-sm-9">
        {!! Form::text('judul', null, ['class' => 'form-control']) !!}
        <small class="text-danger">{{ $errors->first('judul') }}</small>
    </div>
</div>

{!! Form::hidden('keterangan', null) !!}
{!! Form::hidden('keterangan2', null) !!}
<!--
<div class="form-group{{ $errors->has('keterangan') ? ' has-error' : '' }}">
    {!! Form::label('keterangan', 'Keterangan', ['class' => 'col-sm-3 control-label']) !!}
    <div class="col-sm-9">
        {!! Form::text('keterangan', null, ['class' => 'form-control']) !!}
        <small class="text-danger">{{ $errors->first('keterangan') }}</small>
    </div>
</div>

<div class="form-group{{ $errors->has('keterangan2') ? ' has-error' : '' }}">
    {!! Form::label('keterangan2', 'Keterangan 2', ['class' => 'col-sm-3 control-label']) !!}
    <div class="col-sm-9">
        {!! Form::text('keterangan2', null, ['class' => 'form-control']) !!}
        <small class="text-danger">{{ $errors->first('keterangan2') }}</small>
    </div>
</div>
-->

<div class="form-group{{ $errors->has('link') ? ' has-error' : '' }}">
    {!! Form::label('link', 'Link Artikel', ['class' => 'col-sm-3 control-label']) !!}
    <div class="col-sm-9">
        {!! Form::text('link', null, ['class' => 'form-control']) !!}
        <small class="text-danger">{{ $errors->first('link') }}</small>
    </div>
</div>

@if (!empty($slide->image))
  <div class="form-group">
      {!! Form::label('image', 'Gambar Sebelumnya', ['class' => 'col-sm-3 control-label']) !!}
          <div class="col-sm-9">
              <img src="{{ asset('images/slideshow/thumb/'.$slide->image) }}" class="img img-responsive" />
          </div>
  </div>

  <div class="form-group{{ $errors->has('publish') ? ' has-error' : '' }}">
      {!! Form::label('publish', 'Publish', ['class' => 'col-sm-3 control-label']) !!}
      <div class="col-sm-9">
          {!! Form::select('publish', ['Y'=>'Yes', 'N'=>'No'], $slide->publish, ['class' => 'form-control']) !!}
          <small class="text-danger">{{ $errors->first('publish') }}</small>
      </div>
  </div>
@endif
<div class="form-group{{ $errors->has('image') ? ' has-error' : '' }}">
    {!! Form::label('image', 'Gambar Slideshow', ['class' => 'col-sm-3 control-label']) !!}
        <div class="col-sm-9">
            {!! Form::file('image', ['class' => 'form-control']) !!}
            <small class="text-danger">{{ $errors->first('image') }}</small>
        </div>
</div>

resources/views/slideshow/index.blade.php
@extends('style')
@section('content')
        <div class="panel panel-success">
          <div class="panel-heading">
            <h3 class="panel-title">Daftar slideshow</h3>
          </div>
          <div class="panel-body">
            @if (session()->has('flash_notification.message'))
              <div class="alert alert-{{ session()->get('flash_notification.level') }}">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                {!! session()->get('flash_notification.message') !!}
              </div>
            @endif
            <a href="{{ route('slide.create') }}" class="btn btn-sm btn-primary" style="margin-bottom: 10px;">Tambah</a>

            <div class='table-responsive'>
              <table class='table table-striped table-bordered table-hover table-condensed'>
                <thead>
                  <tr>
                    <th>No</th>
                    <th>Judul</th>
                    <th>Keterangan</th>
                    <th>Url/Link</th>
                    <th>Gambar</th>
                    <th>Aksi</th>
                  </tr>
                </thead>
                <tbody>
                  @foreach ($slide as $d)
                    {!! Form::open(array('url'=>'slide/'.$d->id, 'method'=>'delete')) !!}
                    {!! Form::hidden('_delete', 'DELETE') !!}
                    <tr>
                      <td>{{ $no++ }}</td>
                      <td>{{ $d->judul }}</td>
                      <td>{{ $d->keterangan }}</td>
                      <td>{{ $d->link }}</td>
                      <td><img src="{!! asset('images/slideshow/thumb/'.$d->image) !!}" /></td>
                      <td>
                        <a href="{{ url('slide/'.$d->id.'/edit') }}" class="btn btn-success btn-sm glyphicon glyphicon-pencil"></a>
                        <button type="submit" onclick="javascript: return confirm('Yakin akan di hapus?')" class="btn btn-sm btn-danger glyphicon glyphicon-remove"></button>
                      </td>
                    </tr>
                  {!! Form::close() !!}
                  @endforeach
                </tbody>
              </table>
            </div>

          </div>
          
        </div>

@endsection