routes/web.php
<?php

use App\Http\Controllers\HomeController;
use App\Http\Controllers\SiswaController;

use App\Setting;
use App\Siswa;
use App\Banner;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

Route::get('/', 'HomeController@index');
Route::get('/home', 'HomeController@index');
Route::get('/prosedur', 'HomeController@prosedur');
Route::get('/agenda', 'HomeController@agenda');

Auth::routes();

Route::group(['middleware'=>['auth']], function()
{
  Route::get('logout', '\App\Http\Controllers\Auth\LoginController@logout');
  Route::resource('siswa', 'SiswaController');
  Route::resource('ortu', 'OrtuController');
  Route::get('datalengkap', 'SiswaController@datalengkap');
  Route::get('getpdf/{id?}', 'SiswaController@getPdf');
  Route::get('dashboard', 'HomeController@dashboard');

});

Route::group(['middleware'=>['auth', 'role:admin']], function()
{
  Route::resource('statis', 'StatisController');
  Route::resource('slide', 'SlideshowController');
  Route::resource('banner', 'BannerController');
  Route::resource('user', 'UserController');
  Route::resource('setting', 'SettingController');
  Route::get('datapendaftar/{jenjang?}', 'HomeController@dataPendaftar');
  Route::get('backup', 'HomeController@backup');
  Route::get('viewdata/{id?}', 'HomeController@viewData');
  Route::post('ubahstatus', 'HomeController@ubahStatus');
  Route::get('downloadexcel/{jenjang?}', 'HomeController@downloadExcel');
});


View::composer('sidebar', function($view){
  $view->banner = App\Banner::where('publish', 'Y')->get();
  if (Auth::check())
  {
    $view->siswa = App\Siswa::where('user_id',Auth::user()->id)->first();
  }
});

app/Siswa.php
<?php

namespace App;
use Illuminate\Database\Eloquent\Model;
use App\User;
use App\Status;

class Siswa extends Model
{
    protected $fillable = ['jenjang','nama','tempatlhr','tgllahir','alamatlkp','kodepos','asal','alamatskl','thnlulus','hp','email','foto','user_id'];

    public function user()
    {
      return $this->belongsTo(User::class);
    }

    public function status()
    {
      return $this->hasOne(Status::class);
    }

}

app/Http/Controllers/SiswaController.php
<?php

namespace App\Http\Controllers;
use Illuminate\Http\Request;
use App\Http\Requests\SimpansiswaRequest;
use Illuminate\Support\Facades\Auth;
use App\Siswa;
use App\User;
use App\Ortu;
use App\Statis;
use App\Status;
use PDF;
use Image;
use File;


class SiswaController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
      $data['siswa'] = Siswa::where('user_id',Auth::user()->id)->first();
      return view('siswa.index',$data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('siswa.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(SimpansiswaRequest $request)
    {
      if(!empty($request->file('foto')))
      {
        $image = time().$request->file('foto')->getClientOriginalName(); //ambil nama, simpan divariable $image
        $request->file('foto')->move('foto/', $image); //set upload ke folder
        Image::make(public_path().'/foto/'.$image)->resize(150,200)->save();
      }else {
        $image = "";
      }

      //Simpan Data Siswa
      $data = $request->all();
      $data['tgllahir'] = kalender($request['tgllahir']);
      $data['foto'] = $image;
      $siswa = Siswa::create($data);

      $status = new Status;
      $status->status = 0;
      $siswa->status()->save($status);

      //Update Data User
      $user['name'] = $request['nama'];
      $user['email'] = $request['email'];
      $siswa->user()->update($user);

      return redirect('ortu')->with('Sukses', 'Data telah ditambahkan');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
      $data['siswa'] = Siswa::where('user_id',Auth::user()->id)->first();
      return view('siswa.show',$data);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
      $data['siswa']=Siswa::findOrFail($id);
      return view('siswa.edit',$data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(SimpansiswaRequest $request, $id)
    {
      $siswa = Siswa::findOrFail($id);
      if(!empty($request->file('foto')))
      {
        $image = time().$request->file('foto')->getClientOriginalName(); //ambil nama, simpan divariable $image
        $request->file('foto')->move('foto/', $image); //set upload ke folder
        Image::make(public_path().'/foto/'.$image)->resize(150,200)->save();
        File::delete(public_path().'/foto/'.$siswa->foto);
      }else {
        $image = $siswa->foto;
      }

      //Update Data Siswa
      $data = $request->all();
      $data['tgllahir'] = kalender($request['tgllahir']);
      $data ['foto'] = $image;
      $siswa->update($data);

      //Update Data User
      $user['name'] = $request['nama'];
      $user['email'] = $request['email'];
      $siswa->user()->update($user);
      return redirect('siswa');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
      Siswa::findOrFail($id)->delete();
      return redirect('siswa');
    }

    public function datalengkap()
    {
      $data['siswa'] = Siswa::where('user_id',Auth::user()->id)->first();
      $data['ortu'] = Ortu::where('user_id',Auth::user()->id)->first();
      return view('siswa.datalengkap', $data);
    }

    public function getPdf($id='')
    {
      $user_id = (! empty($id) ? $id : Auth::user()->id);
      $data['siswa'] = Siswa::where('user_id', $user_id)->first();
      $data['ortu'] = Ortu::where('user_id', $user_id)->first();
      $data['pengumuman'] = Statis::where('id', 6)->first();
      $pdf= PDF::loadView('getPdf',$data);
      return $pdf->download($data['siswa']->nama.'.pdf');
    }
}

resources/views/siswa/_datasiswa.blade.php
<div class="panel panel-warning">
  <div class="panel-heading">
    <h3 class="panel-title">Data Siswa</h3>
  </div>
  <div class="panel-body">
    <div class='table-responsive'>
      <table class='table table-striped table-bordered table-hover table-condensed'>
        <tbody>
          <tr>
            <td>Jenjang</td><td>{{ $siswa->jenjang }}</td>
            <td rowspan="12">
              @if ($siswa->foto)
                <img src="{{ asset('foto/'.$siswa->foto) }}" class="img img-responsive img-thumbnail" />
              @endif
            </td>
          </tr>
          <tr>
            <td>Nama Lengkap</td><td>{{ ucfirst($siswa->nama) }}</td>
          </tr>
          <tr>
            <td>Tempat Tanggal Lahir</td><td>{{ ucfirst($siswa->tempatlhr) }}, {{ tgl_indo($siswa->tgllahir) }}</td>
          </tr>
          <tr>
            <td>Alamat Lengkap</td><td>{{ ucfirst($siswa->alamatlkp) }}</td>
          </tr>
          <tr>
            <td>Kode Pos</td><td>{{ $siswa->kodepos }}</td>
          </tr>
          <tr>
            <td>Asal Sekolah</td><td>{{ $siswa->asal }}</td>
          </tr>
          <tr>
            <td>Alamat Sekolah</td><td>{{ ucfirst($siswa->alamatskl) }}</td>
          </tr>
          <tr>
            <td>Tahun Lulus</td><td>{{ $siswa->thnlulus }}</td>
          </tr>
          <tr>
            <td>No. HP</td><td>{{ $siswa->hp }}</td>
          </tr>
          <tr>
            <td>Email</td><td>{{ $siswa->email }}</td>
          </tr>
        </tbody>
      </table>
    </div>
    <div class="pull-right">
      <a href="{{ route('siswa.edit', $siswa->id) }}" class="btn btn-sm btn-info"><i class="fa fa-edit"> </i> EDIT</a>
    </div>
  </div>

</div>

resources/views/siswa/_form.blade.php
<div class="form-group{{ $errors->has('jenjang') ? ' has-error' : '' }}">
    {!! Form::label('jenjang', 'Pilih Jenjang', ['class' => 'col-sm-3 control-label']) !!}
    <div class="col-sm-9">
        {!! Form::select('jenjang', [''=>'', 'MA'=>'MA', 'MTS'=>'MTS'], null, ['class' => 'form-control']) !!}
        <small class="text-danger">{{ $errors->first('jenjang') }}</small>
    </div>
</div>
<div class="form-group{{ $errors->has('nama') ? ' has-error' : '' }}">
    {!! Form::label('nama', 'Nama Lengkap', ['class' => 'col-sm-3 control-label']) !!}
    <div class="col-sm-9">
        {!! Form::text('nama', Auth::user()->name, ['class' => 'form-control']) !!}
        <small class="text-danger">{{ $errors->first('nama') }}</small>
    </div>
</div>
<div class="form-group{{ $errors->has('tempatlhr') ? ' has-error' : '' }}">
    {!! Form::label('tempatlhr', 'Tempat Lahir', ['class' => 'col-sm-3 control-label']) !!}
    <div class="col-sm-9">
        {!! Form::text('tempatlhr', null, ['class' => 'form-control']) !!}
        <small class="text-danger">{{ $errors->first('tempatlhr') }}</small>
    </div>
</div>
<div class="form-group{{ $errors->has('tgllahir') ? ' has-error' : '' }}">
    {!! Form::label('tgllahir', 'Tanggal Lahir', ['class' => 'col-sm-3 control-label']) !!}
    <div class="col-sm-9">
        {!! Form::text('tgllahir', !empty($siswa->tgllahir) ? tgl_indo($siswa->tgllahir) : null, ['class' => 'form-control']) !!}
        <small class="text-danger">{{ $errors->first('tgllahir') }}</small>
    </div>
</div>
<div class="form-group{{ $errors->has('alamatlkp') ? ' has-error' : '' }}">
    {!! Form::label('alamatlkp', 'Alamat Lengkap', ['class' => 'col-sm-3 control-label']) !!}
    <div class="col-sm-9">
        {!! Form::text('alamatlkp', null, ['class' => 'form-control']) !!}
        <small class="text-danger">{{ $errors->first('alamatlkp') }}</small>
    </div>
</div>
<div class="form-group{{ $errors->has('kodepos') ? ' has-error' : '' }}">
    {!! Form::label('kodepos', 'Kode Pos', ['class' => 'col-sm-3 control-label']) !!}
    <div class="col-sm-9">
        {!! Form::text('kodepos', null, ['class' => 'form-control']) !!}
        <small class="text-danger">{{ $errors->first('kodepos') }}</small>
    </div>
</div>
<div class="form-group{{ $errors->has('asal') ? ' has-error' : '' }}">
    {!! Form::label('asal', 'Asal Sekolah', ['class' => 'col-sm-3 control-label']) !!}
    <div class="col-sm-9">
        {!! Form::text('asal', null, ['class' => 'form-control']) !!}
        <small class="text-danger">{{ $errors->first('asal') }}</small>
    </div>
</div>
<div class="form-group{{ $errors->has('alamatskl') ? ' has-error' : '' }}">
    {!! Form::label('alamatskl', 'Alamat Sekolah', ['class' => 'col-sm-3 control-label']) !!}
    <div class="col-sm-9">
        {!! Form::text('alamatskl', null, ['class' => 'form-control']) !!}
        <small class="text-danger">{{ $errors->first('alamatskl') }}</small>
    </div>
</div>
<div class="form-group{{ $errors->has('thnlulus') ? ' has-error' : '' }}">
    {!! Form::label('thnlulus', 'Tahun Lulus', ['class' => 'col-sm-3 control-label']) !!}
    <div class="col-sm-9">
        {!! Form::text('thnlulus', null, ['class' => 'form-control']) !!}
        <small class="text-danger">{{ $errors->first('thnlulus') }}</small>
    </div>
</div>
<div class="form-group{{ $errors->has('hp') ? ' has-error' : '' }}">
    {!! Form::label('hp', 'No. HP', ['class' => 'col-sm-3 control-label']) !!}
    <div class="col-sm-9">
        {!! Form::text('hp', null, ['class' => 'form-control']) !!}
        <small class="text-danger">{{ $errors->first('hp') }}</small>
    </div>
</div>
<div class="form-group{{ $errors->has('email') ? ' has-error' : '' }}">
    {!! Form::label('email', 'Email', ['class' => 'col-sm-3 control-label']) !!}
    <div class="col-sm-9">
        {!! Form::text('email', Auth::user()->email, ['class' => 'form-control']) !!}
        <small class="text-danger">{{ $errors->first('email') }}</small>
    </div>
</div>
<div class="form-group{{ $errors->has('foto') ? ' has-error' : '' }}">
    {!! Form::label('foto', 'File Foto', ['class' => 'col-sm-3 control-label']) !!}
        <div class="col-sm-9">
            {!! Form::file('foto', ['class' => 'form-control']) !!}
            <!-- <p class="help-block">Help block text</p> -->
            <small class="text-danger">{{ $errors->first('foto') }}</small>
        </div>
</div>
{!! Form::hidden('user_id', Auth::user()->id) !!}

resources/views/siswa/create.blade.php
<div class="panel panel-warning">
  <div class="panel-heading">
    <h3 class="panel-title">Formulir Data Siswa</h3>
  </div>
  <div class="panel-body">
    {!! Form::open(['method' => 'POST', 'route' => 'siswa.store', 'files'=>true,'class' => 'form-horizontal']) !!}

        @include('siswa._form')

        <div class="btn-group pull-right">
            {!! Form::submit("Simpan", ['class' => 'btn btn-success']) !!}
        </div>
    {!! Form::close() !!}
  </div>
</div>

resources/views/siswa/datalengkap.blade.php
@extends('style')
@section('content')
  <div class="panel panel-warning">
    <div class="panel-heading">
      <h3 class="panel-title">Data Siswa</h3>
    </div>
    <div class="panel-body">
      @if ($siswa)
      <div class='table-responsive'>
        <table class='table table-striped table-bordered table-hover table-condensed'>
          <tbody>
            <tr>
              <td>STATUS</td>
              <td>
                @if ($siswa->status->status == 0)
                  <button type="button" class="btn btn-sm btn-default">BELUM DITERIMA</button>
                @elseif ($siswa->status->status == 1)
                  <button type="button" class="btn btn-sm btn-success">DITERIMA</button>
                @elseif ($siswa->status->status == 2)
                  <button type="button" class="btn btn-sm btn-danger">TIDAK DITERIMA</button>
                @endif
              </td>
              <td rowspan="12">
                @if ($siswa->foto)
                  <img src="{{ asset('foto/'.$siswa->foto) }}" class="img img-responsive img-thumbnail" />
                @endif
              </td>
            </tr>
            <tr>
              <td>Jenjang</td><td>{{ $siswa->jenjang }}</td>
            </tr>
            <tr>
              <td>Nama Lengkap</td><td>{{ ucfirst($siswa->nama) }}</td>
            </tr>
            <tr>
              <td>Tempat Tanggal Lahir</td><td>{{ ucfirst($siswa->tempatlhr) }}, {{ tgl_indo($siswa->tgllahir) }}</td>
            </tr>
            <tr>
              <td>Alamat Lengkap</td><td>{{ ucfirst($siswa->alamatlkp) }}</td>
            </tr>
            <tr>
              <td>Kode Pos</td><td>{{ $siswa->kodepos }}</td>
            </tr>
            <tr>
              <td>Asal Sekolah</td><td>{{ $siswa->asal }}</td>
            </tr>
            <tr>
              <td>Alamat Sekolah</td><td>{{ ucfirst($siswa->alamatskl) }}</td>
            </tr>
            <tr>
              <td>Tahun Lulus</td><td>{{ $siswa->thnlulus }}</td>
            </tr>
            <tr>
              <td>No. HP</td><td>{{ $siswa->hp }}</td>
            </tr>
            <tr>
              <td>Email</td><td>{{ $siswa->email }}</td>
            </tr>
          </tbody>
        </table>
      </div>
      <div class="pull-right">
        <a href="{{ route('siswa.edit', $siswa->id) }}" class="btn btn-sm btn-info"><i class="fa fa-edit"> </i> EDIT</a>
      </div>
      @else
        <h4>Data Siswa belum dilengkapi <a href="{{ url('siswa') }}" class="btn btn-sm btn-info">Lengkapi Data</a></h4>
      @endif
    </div>

  </div>

  <div class="panel panel-warning">
    <div class="panel-heading">
      <h3 class="panel-title">Data Orang Tua</h3>
    </div>
    <div class="panel-body">
      @if ($ortu)
      <div class='table-responsive'>
        <table class='table table-striped table-bordered table-hover table-condensed'>
          <tbody>
            <tr>
              <td>Nama Ayah</td><td>{{ ucfirst($ortu->ayah) }}</td>
            </tr>
            <tr>
              <td>Nama Ibu</td><td>{{ ucfirst($ortu->ibu) }}</td>
            </tr>
            <tr>
              <td>Nama Wali</td><td>{{ ucfirst($ortu->wali) }}</td>
            </tr>
            <tr>
              <td>Alamat Rumah</td><td>{{ ucfirst($ortu->alamatrmh) }}</td>
            </tr>
            <tr>
              <td>Profesi</td><td>{{ ucfirst($ortu->profesi) }}</td>
            </tr>
          </tbody>
        </table>
      </div>
      <div class="pull-right">
        <a href="{{ url('getpdf') }}" class="btn btn-sm btn-success"> <i class="fa fa-file-pdf-o" aria-hidden="true"></i> &nbsp;DOWNLOAD </a>
        <a href="{{ route('ortu.edit', $ortu->id) }}" class="btn btn-sm btn-info"><i class="fa fa-edit"> </i> EDIT</a>
      </div>
      @else
        <h4>Data Orang Tua belum dilengkapi <a href="{{ url('ortu') }}" class="btn btn-sm btn-info">Lengkapi Data</a></h4>
      @endif
    </div>
  </div>

@endsection

resources/views/siswa/edit.blade.php
@extends('style')
@section('content')

<div class="panel panel-warning">
  <div class="panel-heading">
    <h3 class="panel-title">Edit Data Siswa</h3>
  </div>
  <div class="panel-body">
    {!! Form::model($siswa, ['route' => ['siswa.update', $siswa->id], 'files'=>true, 'class' => 'form-horizontal', 'method' => 'PUT']) !!}

        @include('siswa._form')

        <div class="btn-group pull-right">
            {!! Form::submit("Simpan", ['class' => 'btn btn-success']) !!}
        </div>

    {!! Form::close() !!}
  </div>
</div>


@endsection

resources/views/siswa/index.blade.php
@extends('style')
@section('content')
  @if ($siswa)
    @include('siswa._datasiswa')
  @else
    @include('siswa.create')
  @endif
@endsection